import os

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

from integrators import explicit_euler as integrator
from models import rimless_wheel as model


def calculate_regions_of_attraction(params, eps=5e-2, num_angles=5, num_velocities=5, output_name="roa"):
    # Generate a plot displaying the Regions of Attraction for the system
    # Inputs:
    #   params: model params, as generated by model.generate_params()
    #   eps: epsilon value for determining whether two points/limit cycles are the same
    #   num_angles: number of different initial angles to simulate
    #   num_velocities: number of different initial velocities to simulate
    #   output_name: name of the directory that should be created to put results in
    # Output: None; saves plots as image files

    # Check whether the output directory exists and create it if necessary
    if not os.path.isdir("output"):
        os.mkdir("output")
    if not os.path.isdir(os.path.join("output", output_name)):
        os.mkdir(os.path.join("output", output_name))

    timestep = 1e-3
    sim_time = 10.0

    # List to keep attractors we find
    # If a phase trajectory re-visits a point (or gets within a tiny epsilon value),
    # then we can conclude that this forms a limit cycle / attractor
    attractors = []

    # Search space
    half_spoke_angle = np.pi / float(params["num_spokes"])  # half-angle between spokes, radians
    initial_angles = np.linspace(
        -half_spoke_angle + params["slope_angle"], half_spoke_angle + params["slope_angle"], num_angles
    )
    initial_velocities = np.linspace(0, 5, num_velocities)
    print(f"Initial angles: {initial_angles}")
    print(f"Initial velocities: {initial_velocities}")

    # Regions of attraction
    space_size = (initial_angles.size, initial_velocities.size)
    regions = -1 * np.ones(space_size)

    # Search over all initial states
    for pt_idx in range(space_size[0] * space_size[1]):
        print(f"{100 * pt_idx / (space_size[0] * space_size[1]):.1f}% done")
        # Get initial conditions
        angle_idx = pt_idx % space_size[0]
        vel_idx = pt_idx // space_size[1]
        initial_state = np.array(
            [initial_angles[angle_idx], initial_velocities[vel_idx]]
        )

        # Simulate system
        time_traj, state_traj = integrator.integrate(
            params, model, initial_state, timestep, sim_time
        )

        # Verify attractor
        this_attractor = None
        diff = np.linalg.norm(state_traj[:, [-1]] - state_traj, axis=0)
        repeated_points = (diff[: -int(0.1 / timestep)] < eps).nonzero()[0]  # Exclude the last 0.1 seconds. Don't really remember why I decided to do this tbh
        if repeated_points.size > 0:
            # There is at least one repeated point
            idx = np.max(repeated_points)
            # print(f"This state leads to an attractor of cycle duration {time_traj[-1] - time_traj[idx]:.3f} seconds")
            this_attractor = state_traj[:, idx:]

        if this_attractor is not None:
            # We need to see whether we have already found this attractor
            # print("Looking over our already-found attractors...")
            already_found = False
            for att_idx in range(len(attractors)):
                # Check an attractor that we had already found against every point in the attractor from this state point
                no_match = False
                for this_att_idx in range(this_attractor.shape[1]):
                    all_comparisons = np.linalg.norm(
                        attractors[att_idx] - this_attractor[:, [this_att_idx]], axis=0
                    )
                    if np.min(all_comparisons) > eps:
                        # This point doesn't have a close match in any of this attractor's points
                        # We can move on to the next attractor
                        no_match = True
                        break
                if not no_match:
                    # Every point on this_attractor has a match in an attractor that we had already found!
                    # print("Found a match")
                    already_found = True
                    regions[angle_idx, vel_idx] = att_idx
                    break
            if not already_found:
                # Didn't find a match. This must be a new attractor!
                # print("Found no matches")
                attractors.append(this_attractor)
                regions[angle_idx, vel_idx] = len(attractors) - 1
        else:
            # No attractor here. Maybe we didn't let the simulation run long enough?
            # print("No attractor")
            regions[angle_idx, vel_idx] = -1

    print("Done!")
    plt.clf()
    im = plt.imshow(regions.T, origin="lower", extent=(initial_angles[0],initial_angles[-1],initial_velocities[0],initial_velocities[-1]))
    plt.gca().set_aspect((initial_angles[-1] - initial_angles[0]) / (initial_velocities[-1] - initial_velocities[0]))
    plt.xlabel("Initial Angle (radians)")
    plt.ylabel("Initial Velocity (rad/s)")
    plt.title("Regions of Attraction")

    # imshow levels legend courtesy of:
    # https://stackoverflow.com/questions/25482876/how-to-add-legend-to-imshow-in-matplotlib
    # Get the colors of the values, according to the colormap used by imshow
    colors = [im.cmap(im.norm(value)) for value in range(len(attractors))]
    # create a patch (proxy artist) for every color
    patches = [
        mpatches.Patch(color=colors[i], label=f"Attractor {i}")
        for i in range(len(attractors))
    ]
    # Put those patched as legend-handles into the legend
    plt.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.0)
    # Finish and display/save the plot
    # plt.grid(True)
    # plt.show()
    plt.tight_layout()
    plt.savefig(os.path.join("output", output_name, "regions.png"))

    for att_idx in range(len(attractors)):
        plt.clf()
        plt.plot(attractors[att_idx][0, :], attractors[att_idx][1, :], "bo:")
        plt.xlabel("Angle (radians)")
        plt.ylabel("Angular Velocity (rad/s)")
        plt.title(f"Attractor {att_idx}")
        # plt.show()
        plt.tight_layout()
        plt.savefig(os.path.join("output", output_name, f"attractor_{att_idx}.png"))


def calculate_poincare_return_map(params, initial_state, perturbation_mag=0.1, output_name="poincare"):
    # Calculate the Return Map of an orbit using a Poincare section
    # Also calculate the slope of the Return Map around its fixed point
    # Inputs:
    #   params: model params to use, such as those generated by model.generate_params()
    #   initial_state: 2xn array representing the initial angle and angular velocity of the wheel
    #   perturbation_mag: the magnitude of perturbations used to calculate the fixed point slope
    #   output_name: name of the directory that should be created to put results in
    # Outputs: None; saves plots to the provided directory

    # Check whether the output directory exists and create it if necessary
    if not os.path.isdir("output"):
        os.mkdir("output")
    if not os.path.isdir(os.path.join("output", output_name)):
        os.mkdir(os.path.join("output", output_name))
    
    # The model.dynamics() function adds contact states to the provided list
    # Maybe that's not ideal...
    poincare_section = []
    _ = integrator.integrate(
        params,
        model,
        initial_state,
        timestep,
        sim_time,
        dynamics_args={"poincare_section": poincare_section},
    )

    if len(poincare_section) == 0:
        print("Unable to create return map")
        return

    # Plot crossings
    plt.figure()
    min_vel = min([p[1] for p in poincare_section])
    max_vel = max([p[1] for p in poincare_section])
    plt.plot(
        [min_vel * 0.9, 1.1 * max_vel],
        [0.9 * min_vel, 1.1 * max_vel],
        label="Identity Line",
    )
    plt.xlabel("Previous value of Angular Velocity (rad/s)")
    plt.ylabel("Next value of Angular Velocity (rad/s)")
    plt.legend()
    plt.plot(
        [p[1] for p in poincare_section[:-1]],
        [p[1] for p in poincare_section[1:]],
        "rx:",
    )
    if len(poincare_section) < 2:
        plt.title("Return Map (Failed)")
        plt.savefig(os.path.join("output", output_name, "return_map.png"))
        print("Not enough points in Poincare section; did we reach a good attractor?")
        return

    # Estimate the fixed point automatically by looking at the most recent Poincare point
    fixed_point_state = poincare_section[-1]
    print(f"Computer-estimated fixed point: {fixed_point_state[1]}")

    # Floquet Multiplier
    # Perturb the fixed point slightly
    perturbation_sim_time = 5.0  # doesn't need to be long
    perturbation = np.array([0.0, perturbation_mag])
    # Positive perturbation
    poincare_section = []
    _ = integrator.integrate(
        params,
        model,
        fixed_point_state + perturbation,
        timestep,
        perturbation_sim_time,
        dynamics_args={"poincare_section": poincare_section},
    )
    if len(poincare_section) == 0:
        plt.title("Return Map (Floquet Multiplier Failure)")
        plt.savefig(os.path.join("output", output_name, "return_map.png"))
        print("Not enough points in Poincare section; did we reach a good attractor?")
        return
    positive_perturbation_state = poincare_section[0]
    # Negative perturbation
    poincare_section = []
    _ = integrator.integrate(
        params,
        model,
        fixed_point_state - perturbation,
        timestep,
        perturbation_sim_time,
        dynamics_args={"poincare_section": poincare_section},
    )
    if len(poincare_section) == 0:
        plt.title("Return Map (Floquet Multiplier Failure)")
        plt.savefig(os.path.join("output", output_name, "return_map.png"))
        print("Not enough points in Poincare section; did we reach a good attractor?")
        return
    negative_perturbation_state = poincare_section[0]
    # Calculate slope at fixed point
    fixed_point_slope = (
        positive_perturbation_state[1] - negative_perturbation_state[1]
    ) / (2 * perturbation_mag)
    print(f"The fixed point slope is {fixed_point_slope}")
    # This value is less than 1, demonstrating how neighboring orbits converge towards the stable limit cycle

    plt.suptitle("Return Map for Angular Velocity and Identity Line")
    plt.title(
        f"Fixed Point at {fixed_point_state[1]:.2f}; Floquet Multiplier {fixed_point_slope:.2f}"
    )
    plt.savefig(os.path.join("output", output_name, "return_map.png"))


if __name__ == "__main__":
    # Main script
    # I just like how this looks
    
    # Create the output directory
    if not os.path.isdir("output"):
        os.mkdir("output")
    
    # Generate default param values (contains slope angle, number of spokes, etc.)
    params = model.generate_params()

    print(f"Half-spoke angle is {np.pi / float(params["num_spokes"])}")
    print(f"Smallest possible angle without colliding is {params["slope_angle"] - np.pi / float(params["num_spokes"])}")
    print(f"Largest possible angle without colliding is {params["slope_angle"] + np.pi / float(params["num_spokes"])}")
    
    # State is stance angle (in the range for one spoke) and stance angular velocity
    initial_state = np.array([0.0, 1.0])
    
    timestep = 1e-3
    sim_time = 5.0  # 5.0 seconds is generally enough to reach a recognizable attractor
    
    time_traj, state_traj = integrator.integrate(params, model, initial_state, timestep, sim_time)
    kinetic_energy, potential_energy = model.calculate_energy(state_traj, params)
    
    # Plot the angle over time
    plt.figure()
    plt.plot(time_traj, state_traj[0], 'bo:', alpha=0.25, label="Angle")
    plt.xlabel("Time (s)")
    plt.ylabel("Angle (radians)")
    plt.title("Rimless Wheel Angle vs Time")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join("output", "trajectory.png"))
    plt.show()

    # Phase diagram: velocity vs angle
    plt.figure()
    plt.plot(state_traj[0], state_traj[1], 'bo:', alpha=0.05, label="Trajectory")
    plt.xlabel("Angle (radians)")
    plt.ylabel("Angular Velocity (rad/s)")
    plt.title("Rimless Wheel Phase Portrait")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join("output", "phase_diagram.png"))
    plt.show()

    # Plot the system energy over time
    plt.figure()
    plt.plot(time_traj, potential_energy, 'bo:', alpha=0.25, label="Potential energy")
    plt.plot(time_traj, kinetic_energy, 'ro:', alpha=0.25, label="Kinetic energy")
    plt.plot(time_traj, potential_energy + kinetic_energy, 'go:', alpha=0.25, label="Total energy")
    plt.xlabel("Time (s)")
    plt.ylabel("Energy (J)")
    plt.title("Pendulum energy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join("output", "system_energy.png"))
    plt.show()

    # Sweeping inclinations and number of spokes
    # This includes the original, default param values, so we'll just lump that in here too
    # Please note that the output plots of this function are saved as images in output/{output_name}
    if True:  # Change to False to disable the costly sweep
        initial_state = np.array([0.0, 1.0])
        for slope_angle in np.linspace(0,0.35,7):
            params = model.generate_params()
            params["slope_angle"] = slope_angle
            output_name = f"angle_{slope_angle:.2f}".replace(".","-")
            calculate_regions_of_attraction(params, num_angles=50, num_velocities=50, output_name=output_name)
            calculate_poincare_return_map(params, initial_state=initial_state, output_name=output_name)

        for num_spokes in (6, 7, 8, 9, 10, 11, 12):
            params = model.generate_params()
            params["num_spokes"] = num_spokes
            output_name = f"{num_spokes}_spokes".replace(".", "-")
            calculate_regions_of_attraction(params, num_angles=50, num_velocities=50, output_name=output_name)
            calculate_poincare_return_map(params, initial_state=initial_state, output_name=output_name)

