from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, PillowWriter

from integrators import rk4 as integrator
from models import inverted_pendulum_walker as model


def visualize(time_traj, state_traj, output_name="assignment_2"):
    # Generate an animation of the walker walking, from the perspective as an inverted pendulum
    # Inputs:
    #   time_traj: n-length array of time values
    #   state_traj: 2xn array of state values that correspond to the times in time_traj at the same index
    #   output_name: name of output directory
    # Output: None, displays and saves an animation

    fig, ax = plt.subplots(figsize=(8, 5), layout="constrained")

    def draw_frame(index):
        # The massless swing leg is repositioned instantaneously at each impact.
        model.visualize(state_traj[:, index], params, ax=ax)
        ax.set_title(f"t = {time_traj[index]:.2f} s")

    # Simulate at a small timestep, but render only 25 frames per second.
    fps = 25
    frame_stride = round(1 / (fps * timestep))
    frame_indices = list(range(0, time_traj.size, frame_stride))
    if frame_indices[-1] != time_traj.size - 1:
        frame_indices.append(time_traj.size - 1)

    animation = FuncAnimation(
        fig, draw_frame, frames=frame_indices, interval=1000 / fps, repeat=False
    )
    output = Path(f"output-assignment2/{output_name}")
    output.mkdir(parents=True, exist_ok=True)
    animation.save(output / "walker.gif", writer=PillowWriter(fps=fps))

    # To save an MP4 instead, install FFmpeg and use:
    # animation.save(output / "walker.mp4", writer="ffmpeg", fps=fps)
    print(f"Saved {output / 'walker.gif'}.")
    plt.show()


def simulate_walker(params, initial_state, timestep, sim_time, desired_number_of_steps, ankle_controller_map, ankle_controller_bounds, poincare_section=None):
    # Simulate the walker for either some number of steps or some time, whichever comes first
    # Input:
    #   params: dict of params as generated by generate_params()
    #   initial_state: 2x1 array, initial state of the system
    #   timestep: time between steps; usually something like 1e-3, in seconds
    #   sim_time: maximum time of simulation, in seconds
    #   desired_number_of_steps: maximum number of steps the walker can take
    #   ankle_controller_map: 100x100 array representing where to enable ankle controller
    #   ankle_controller_bounds: 2x100 array representing the limits of the ankle_controller_map
    #   poincare_map: if a list is provided, angular velocities that occur when the pendulum is at angle 0 are appended
    # Output: length-n array of times; 2xn array of state trajectory; number of completed steps

    n_timesteps = round(sim_time / timestep) + 1
    time_traj = np.arange(n_timesteps) * timestep
    state_traj = np.zeros((2, n_timesteps))
    state_traj[:, 0] = initial_state
    completed_steps = 0

    # Simulation loop.
    for step, t in enumerate(time_traj[:-1]):
        state = state_traj[:, step]

        if model.ankle_torque_guard(state, params, ankle_controller_map, ankle_controller_bounds):
            model.update_ankle_torque(state, params)
        else:
            params["ankle_torque"] = 0.0  # need to reset to disable control

        #next_state = state + timestep * model.dynamics(t, state, params)
        next_state = integrator.integrate_step(params, model, state, t, timestep)

        if poincare_section is not None and model.poincare_map_guard(state, next_state, params):
            # Calculate the velocity at the map angle using energy
            _, vertical_potential = model.calculate_energy(np.array([0,0]), params)
            next_kinetic, next_potential = model.calculate_energy(next_state, params)
            intersect_kinetic = (next_kinetic + next_potential) - vertical_potential
            intersect_ang_vel = (
                np.sqrt(intersect_kinetic / (0.5 * params["mass"]))
                / params["length"]
            )
            poincare_section.append(intersect_ang_vel)

        if model.step_transition_guard(state, next_state, params):
            next_state = model.step_transition_dynamics(next_state, params)
            completed_steps += 1

        state_traj[:, step + 1] = next_state
        if completed_steps == desired_number_of_steps:
            break

    time_traj = time_traj[: step + 2]
    state_traj = state_traj[:, : step + 2]
    return time_traj, state_traj, completed_steps


def calculate_ankle_roa(params):
    # Determine RoA of the ankle controller
    # Inputs:
    #   params: dict of params as generated by generate_params()

    timestep = 1e-3
    sim_time = 3.0

    num_angles = 100
    initial_angles = np.linspace(
        -params["angle_of_attack"] + params["incline"], params["angle_of_attack"] + params["incline"], num_angles
    )
    num_velocities = 100
    initial_velocities = np.linspace(0, 2, num_velocities)

    dummy_controller_bounds = np.vstack((initial_angles, initial_velocities))
    dummy_controller_map = np.ones((num_angles,num_velocities))

    stop_map = np.ones((initial_angles.size, initial_velocities.size))
    for ang_idx in range(initial_angles.size):
        print(f"Calculating ankle controller RoA: {100*ang_idx/initial_angles.size:.2f}% done")
        initial_angle = initial_angles[ang_idx]
        for ang_vel_idx in range(initial_velocities.size):
            initial_ang_vel = initial_velocities[ang_vel_idx]
            initial_state = np.array([initial_angle, initial_ang_vel])
            time_traj, state_traj, completed_steps = simulate_walker(
                params,
                initial_state,
                timestep,
                sim_time,
                1,
                dummy_controller_map,
                dummy_controller_bounds
            )
            # Tracking the number of steps actually makes this correlation super easy
            # If a step was taken, then we know that the ankle controller wasn't able to slow the walker to a stop
            # Also, if the final state isn't near static vertical, then we know it must have gone off the rails
            if completed_steps > 0 or np.linalg.norm(state_traj[:,-1]) > 0.05:
                stop_map[ang_idx, ang_vel_idx] = 0

    # Save region of attraction for future use in one file
    # Save the bounds of the map in another file
    params_hash = model.hash_params(params)
    controller_output = Path("output-assignment2/controller_data")
    controller_output.mkdir(parents=True, exist_ok=True)
    np.save(controller_output / f"map_{params_hash}", stop_map)
    combined_bounds = np.vstack((initial_angles, initial_velocities))
    np.save(controller_output / f"bounds_{params_hash}", combined_bounds)

    # Generate a plot showing this RoA
    plt.clf()
    im = plt.imshow(stop_map.T, origin="lower", extent=(initial_angles[0],initial_angles[-1],initial_velocities[0],initial_velocities[-1]))
    plt.gca().set_aspect((initial_angles[-1] - initial_angles[0]) / (initial_velocities[-1] - initial_velocities[0]))
    plt.xlabel("Initial Angle (radians)")
    plt.ylabel("Initial Velocity (rad/s)")
    plt.title("Region of Stoppage")

    # Finish and display/save the plot
    plt.tight_layout()
    plt.savefig(controller_output / "stop_map.png")
    # plt.show()


def load_ankle_controller(params):
    # Load the Region of Attraction data for the walker's ankle torque controller
    # Inputs:
    #   params: dict of params as generated by generate_params()
    # Outputs: stop map (100x100), bounds (2x100)

    params_hash = model.hash_params(params)

    map_path = Path(f"output-assignment2/controller_data/map_{params_hash}.npy")
    bounds_path = Path(f"output-assignment2/controller_data/bounds_{params_hash}.npy")
    if not (map_path.exists() and bounds_path.exists()):
        # Calculate new ankle controller RoA data
        calculate_ankle_roa(params)

    stop_map = np.load(map_path)
    bounds = np.load(bounds_path)

    return stop_map, bounds


def plot_poincare_section(poincare_section):
    # Plot the step-to-step points of the Poincare section (e.g. (x0,x1), (x1,x2), (x2,x3), ...)
    # Inputs:
    #   poincare_map: list of angular velocity values that the system experienced at the same angle
    # Output: None, saves a plot

    if len(poincare_section) < 2:
        plt.title("Return Map (Failed)")
        poincare_path = Path("output-assignment2/assignment_2/return_map.png")
        plt.savefig(poincare_path)
        print("Not enough points in Poincare section; did we reach a good attractor?")
    else:
        plt.figure()
        min_vel = min(poincare_section)
        max_vel = max(poincare_section)
        plt.plot(
            [min_vel * 0.9, 1.1 * max_vel],
            [0.9 * min_vel, 1.1 * max_vel],
            label="Identity Line",
        )
        plt.xlabel("Previous value of Angular Velocity (rad/s)")
        plt.ylabel("Next value of Angular Velocity (rad/s)")
        plt.legend()
        plt.plot(
            poincare_section[:-1],
            poincare_section[1:],
            "rx:",
        )
        plt.show()

        # Estimate the fixed point automatically by looking at the most recent Poincare point
        fixed_point_vel = poincare_section[-1]
        print(f"Computer-estimated fixed point: {fixed_point_vel}")


# Fixed controls for this visualization example.
params = model.generate_params()

ankle_controller_bounds, ankle_controller_map = load_ankle_controller(params)

initial_state = np.array([0.0, 1.0])
timestep = 1e-3
sim_time = 5.0
desired_number_of_steps = 8

poincare_section = []

time_traj, state_traj, completed_steps = simulate_walker(
        params,
        initial_state,
        timestep,
        sim_time,
        desired_number_of_steps,
        ankle_controller_bounds,
        ankle_controller_map,
        poincare_section=poincare_section,
    )

print(f"Simulated for {time_traj[-1]} seconds; recorded {completed_steps} steps")
#visualize(time_traj, state_traj)


# Build a lookup table of leg angle control actions
print("Building step angle graph")
max_initial_velocity = np.sqrt(2 * params["gravity"] / params["length"])
num_actions = 10
actions = np.linspace(np.pi/8, np.pi/7, num_actions)

# We need some data structure to store the connections between initial velocities (nodes)
# We can probably fairly assume that each control angle at each initial velocity will only lead to one other velocity
connection_tol = 0.05  # tolerance between states for equivalence, rad/s
connections = {max_initial_velocity: {}, 0: {}}  # graph; structured as {upstream velocity: {action: downstream velocity, action: downstream velocity, ...}, ...}
# Instead of doing this in a simple and logical way, we can set this up as a graph traversal problem!
# We can guide the search with a stack to construct the full extent of the graph
# Each entry in the stack will be composed of an ordered pair, (velocity, action)
# When we simulate a pair, we can remove it from the stack and, if they're not in the graph, add all actions of the next state
stack = [(max_initial_velocity, actions[i]) for i in range(num_actions)]

# Seed with some initial velocities
# This kind of negates the usefulness of the stack-based expansion
# Well, I thought it was a cool idea
for vel in np.arange(0, max_initial_velocity, connection_tol):
    connections[vel] = {}
    for act in actions:
        stack.append((vel, act))

# Constant simulation properties
timestep = 1e-3
sim_time = 5.0
desired_number_of_steps = 2  # We expect there to be one step, but we'll look at the Poincare section before the second one

while len(stack) > 0:
    print(f"Stack size: {len(stack)}")
    # Just to make sure we start with the same params every time
    # Fixed controls for this visualization example.
    params = model.generate_params()

    case = stack.pop()
    initial_velocity = case[0]
    action = case[1]
    params["angle_of_attack"] = action
    initial_state = np.array([0.0, initial_velocity])

    poincare_section = []

    time_traj, state_traj, completed_steps = simulate_walker(
        params,
        initial_state,
        timestep,
        sim_time,
        desired_number_of_steps,
        ankle_controller_bounds,
        ankle_controller_map,
        poincare_section=poincare_section,
    )

    # If the Poincare section didn't register anything, then this IC leads to stability or a failure state
    if len(poincare_section) == 0:
        if abs(state_traj[0,-1]) < connection_tol and abs(state_traj[1,-1]) < connection_tol:
            # Stable
            next_velocity = 0
        else:
            next_velocity = -1  # failure state
    else:
        next_velocity = poincare_section[0]

    # Since we're using the velocity values directly, equivalence between velocities should be within a tolerance
    # We will assume that our initial_velocity already went through this process and matches to something in the connections
    already_in_graph = False
    for graph_vel in connections:
        if abs(graph_vel - next_velocity) < connection_tol:
            # These points are practically the same
            next_velocity = graph_vel
            already_in_graph = True

    connections[initial_velocity][action] = next_velocity

    if not already_in_graph:
        connections[next_velocity] = {}
        stack += [(next_velocity, a) for a in actions]

# Visualize the graph as a table
# Build an actual 2D array of initial velocities and control angles
lookup_table = np.zeros((len(connections.keys())-1, num_actions))
for vel_idx, vel in enumerate([v for v in sorted(connections.keys()) if v != -1]):
    for act_idx in range(num_actions):
        lookup_table[vel_idx][act_idx] = connections[vel][actions[act_idx]]


im = plt.imshow(lookup_table, origin="lower", extent=(actions[0],actions[-1],0,max_initial_velocity))
plt.gca().set_aspect((actions[-1] - actions[0]) / (max_initial_velocity - 0))
cbar = plt.gcf().colorbar(im)
cbar.set_label('Next angular velocity',size=12,rotation=270)
plt.xlabel("Control angle (radians)")
plt.ylabel("Angular velocity at $\\theta = 0$ (rad/s)")
plt.title("Control Table\nVelocity of -1 denotes failure")
plt.tight_layout()
plt.savefig(Path("output-assignment2/assignment_2/table.png"))
plt.show()


# Create a graph to visualize all the connections
# This is just pure connections, not the values of actions that actually lead to these connections
plt.figure()
t = -np.linspace(-np.pi/2, np.pi/2,25)
# Mess with t a little bit to put more points around 0, which makes it look smoother in this plot
t = ((np.pi/2) / np.pow(np.pi/2,3)) * np.pow(t,3)
for node in connections:
    for edge in connections[node]:
        # Draw an arc going to the next node
        next_node = connections[node][edge]
        switch = 1
        col = 'g'
        if next_node == -1:
            switch = -1
            col = 'r'
        rad = (node - next_node) / 2
        plt.plot(switch * abs(rad) * np.cos(t), ((node + next_node) / 2) + rad * np.sin(t), col+'-', alpha=0.2)
plt.plot([0 for key in connections if key != -1], [key for key in connections if key != -1], "bo")
plt.plot(0, -1, 'bx')
#plt.axis("equal")
plt.title("Poincare Section Velocity Graph")
plt.ylabel("Angular velocity at $\\theta = 0$")
plt.savefig(Path("output-assignment2/assignment_2/poincare.png"))
plt.show()


# Plot initial velocities by number of steps to stability
# The way that we have stored the graph makes this obnoxiously difficult
# This might be easiest if we just reverse connections the graph
reversed_connections = {}
for node in connections:
    for edge in connections[node]:
        if connections[node][edge] not in reversed_connections:
            reversed_connections[connections[node][edge]] = []
        reversed_connections[connections[node][edge]].append(node)
# Note that the keys of reversed_connections are only those nodes which can be reached by another node
# e.g. the maximum initial velocity isn't a key because there's no way to get to it, but it is represented inside of some of the keys' lists

# Now we can traverse the reversed graph, starting from 0, and record how many steps are required to get anywhere
# We can also assemble a lookup table of optimal controls to make the visual look prettier
steps = {0:0}
optimal_connections = {}
stack = [0]
while len(stack) > 0:
    print(f"Stack size: {len(stack)}")
    node = stack.pop()
    if node in reversed_connections:
        for edge in reversed_connections[node]:
            if edge not in steps:
                steps[edge] = steps[node] + 1
                optimal_connections[edge] = node
                stack.append(edge)
            else:
                if steps[edge] > steps[node]+1:
                    # Replace
                    steps[edge] = steps[node]+1
                    optimal_connections[edge] = node

# Plot the steps
plt.figure()
for s in reversed(range(max([steps[i] for i in steps])+1)):
    applicable_nodes = [i for i in steps if steps[i] == s]
    if s != 0:
        for node in applicable_nodes:
            plt.plot((s, s-1), (node, optimal_connections[node]), 'g-')
    plt.plot([s] * len(applicable_nodes), applicable_nodes, "bo")
plt.title("Steps Required for Stability")
plt.xlabel("Steps before stability")
plt.ylabel("Angular velocity at $\\theta = 0$")
plt.savefig(Path("output-assignment2/assignment_2/steps.png"))
plt.show()
