from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, PillowWriter

from integrators import rk4 as integrator
from models import inverted_pendulum_walker as model


def visualize(time_traj, state_traj, output_name="assignment_2"):
    # Generate an animation of the walker walking, from the perspective as an inverted pendulum
    # Inputs:
    #   time_traj: n-length array of time values
    #   state_traj: 2xn array of state values that correspond to the times in time_traj at the same index
    #   output_name: name of output directory
    # Output: None, displays and saves an animation

    fig, ax = plt.subplots(figsize=(8, 5), layout="constrained")

    def draw_frame(index):
        # The massless swing leg is repositioned instantaneously at each impact.
        model.visualize(state_traj[:, index], params, ax=ax)
        ax.set_title(f"t = {time_traj[index]:.2f} s")

    # Simulate at a small timestep, but render only 25 frames per second.
    fps = 25
    frame_stride = round(1 / (fps * timestep))
    frame_indices = list(range(0, time_traj.size, frame_stride))
    if frame_indices[-1] != time_traj.size - 1:
        frame_indices.append(time_traj.size - 1)

    animation = FuncAnimation(
        fig, draw_frame, frames=frame_indices, interval=1000 / fps, repeat=False
    )
    output = Path(f"output-assignment2/{output_name}")
    output.mkdir(parents=True, exist_ok=True)
    animation.save(output / "walker.gif", writer=PillowWriter(fps=fps))

    # To save an MP4 instead, install FFmpeg and use:
    # animation.save(output / "walker.mp4", writer="ffmpeg", fps=fps)
    print(f"Saved {output / 'walker.gif'}.")
    plt.show()


def simulate_walker(params, initial_state, timestep, sim_time, desired_number_of_steps, ankle_controller_map, ankle_controller_bounds, poincare_section=None):
    # Simulate the walker for either some number of steps or some time, whichever comes first
    # Input:
    #   params: dict of params as generated by generate_params()
    #   initial_state: 2x1 array, initial state of the system
    #   timestep: time between steps; usually something like 1e-3, in seconds
    #   sim_time: maximum time of simulation, in seconds
    #   desired_number_of_steps: maximum number of steps the walker can take
    #   ankle_controller_map: 100x100 array representing where to enable ankle controller
    #   ankle_controller_bounds: 2x100 array representing the limits of the ankle_controller_map
    #   poincare_map: if a list is provided, angular velocities that occur when the pendulum is at angle 0 are appended
    # Output: length-n array of times; 2xn array of state trajectory; number of completed steps

    n_timesteps = round(sim_time / timestep) + 1
    time_traj = np.arange(n_timesteps) * timestep
    state_traj = np.zeros((2, n_timesteps))
    state_traj[:, 0] = initial_state
    completed_steps = 0

    # Simulation loop.
    for step, t in enumerate(time_traj[:-1]):
        state = state_traj[:, step]

        if model.ankle_torque_guard(state, params, ankle_controller_map, ankle_controller_bounds):
            model.update_ankle_torque(state, params)
        else:
            params["ankle_torque"] = 0.0  # need to reset to disable control

        #next_state = state + timestep * model.dynamics(t, state, params)
        next_state = integrator.integrate_step(params, model, state, t, timestep)

        if poincare_section is not None and model.poincare_map_guard(state, next_state, params):
            # Calculate the velocity at the map angle using energy
            _, vertical_potential = model.calculate_energy(np.array([0,0]), params)
            next_kinetic, next_potential = model.calculate_energy(next_state, params)
            intersect_kinetic = (next_kinetic + next_potential) - vertical_potential
            intersect_ang_vel = (
                np.sqrt(intersect_kinetic / (0.5 * params["mass"]))
                / params["length"]
            )
            poincare_section.append(intersect_ang_vel)

        if model.step_transition_guard(state, next_state, params):
            next_state = model.step_transition_dynamics(next_state, params)
            completed_steps += 1

        state_traj[:, step + 1] = next_state
        if completed_steps == desired_number_of_steps:
            break

    time_traj = time_traj[: step + 2]
    state_traj = state_traj[:, : step + 2]
    return time_traj, state_traj, completed_steps


def calculate_ankle_roa(params):
    # Determine RoA of the ankle controller
    # Inputs:
    #   params: dict of params as generated by generate_params()

    timestep = 1e-3
    sim_time = 3.0

    num_angles = 100
    initial_angles = np.linspace(
        -params["angle_of_attack"] + params["incline"], params["angle_of_attack"] + params["incline"], num_angles
    )
    num_velocities = 100
    initial_velocities = np.linspace(0, 2, num_velocities)

    dummy_controller_bounds = np.vstack((initial_angles, initial_velocities))
    dummy_controller_map = np.ones((num_angles,num_velocities))

    stop_map = np.ones((initial_angles.size, initial_velocities.size))
    for ang_idx in range(initial_angles.size):
        print(f"Calculating ankle controller RoA: {100*ang_idx/initial_angles.size:.2f}% done")
        initial_angle = initial_angles[ang_idx]
        for ang_vel_idx in range(initial_velocities.size):
            initial_ang_vel = initial_velocities[ang_vel_idx]
            initial_state = np.array([initial_angle, initial_ang_vel])
            time_traj, state_traj, completed_steps = simulate_walker(params, initial_state, timestep, sim_time, 1, dummy_controller_map, dummy_controller_bounds)
            # Tracking the number of steps actually makes this correlation super easy
            # If a step was taken, then we know that the ankle controller wasn't able to slow the walker to a stop
            # Also, if the final state isn't near static vertical, then we know it must have gone off the rails
            if completed_steps > 0 or np.linalg.norm(state_traj[:,-1]) > 0.05:
                stop_map[ang_idx, ang_vel_idx] = 0

    # Save region of attraction for future use in one file
    # Save the bounds of the map in another file
    params_hash = model.hash_params(params)
    controller_output = Path("output-assignment2/controller_data")
    controller_output.mkdir(parents=True, exist_ok=True)
    np.save(controller_output / f"map_{params_hash}", stop_map)
    combined_bounds = np.vstack((initial_angles, initial_velocities))
    np.save(controller_output / f"bounds_{params_hash}", combined_bounds)

    # Generate a plot showing this RoA
    plt.clf()
    im = plt.imshow(stop_map.T, origin="lower", extent=(initial_angles[0],initial_angles[-1],initial_velocities[0],initial_velocities[-1]))
    plt.gca().set_aspect((initial_angles[-1] - initial_angles[0]) / (initial_velocities[-1] - initial_velocities[0]))
    plt.xlabel("Initial Angle (radians)")
    plt.ylabel("Initial Velocity (rad/s)")
    plt.title("Region of Stoppage")

    # Finish and display/save the plot
    plt.tight_layout()
    plt.savefig(controller_output / "stop_map.png")
    # plt.show()


def load_ankle_controller(params):
    # Load the Region of Attraction data for the walker's ankle torque controller
    # Inputs:
    #   params: dict of params as generated by generate_params()
    # Outputs: stop map (100x100), bounds (2x100)

    params_hash = model.hash_params(params)

    map_path = Path(f"output-assignment2/controller_data/map_{params_hash}.npy")
    bounds_path = Path(f"output-assignment2/controller_data/bounds_{params_hash}.npy")
    if not (map_path.exists() and bounds_path.exists()):
        # Calculate new ankle controller RoA data
        calculate_ankle_roa(params)

    stop_map = np.load(map_path)
    bounds = np.load(bounds_path)

    return stop_map, bounds


def plot_poincare_section(poincare_section):
    # Plot the step-to-step points of the Poincare section (e.g. (x0,x1), (x1,x2), (x2,x3), ...)
    # Inputs:
    #   poincare_map: list of angular velocity values that the system experienced at the same angle
    # Output: None, saves a plot

    if len(poincare_section) < 2:
        plt.title("Return Map (Failed)")
        poincare_path = Path("output-assignment2/assignment_2/return_map.png")
        plt.savefig(poincare_path)
        print("Not enough points in Poincare section; did we reach a good attractor?")
    else:
        plt.figure()
        min_vel = min(poincare_section)
        max_vel = max(poincare_section)
        plt.plot(
            [min_vel * 0.9, 1.1 * max_vel],
            [0.9 * min_vel, 1.1 * max_vel],
            label="Identity Line",
        )
        plt.xlabel("Previous value of Angular Velocity (rad/s)")
        plt.ylabel("Next value of Angular Velocity (rad/s)")
        plt.legend()
        plt.plot(
            poincare_section[:-1],
            poincare_section[1:],
            "rx:",
        )
        plt.show()

        # Estimate the fixed point automatically by looking at the most recent Poincare point
        fixed_point_vel = poincare_section[-1]
        print(f"Computer-estimated fixed point: {fixed_point_vel}")


# Fixed controls for this visualization example.
params = {
    "gravity": 9.81,  # m/s^2
    "length": 1.0,  # m
    "mass": 1.0,  # kg
    "incline": 0.06,  # rad
    "angle_of_attack": np.pi / 8,  # rad
    "ankle_torque": 0.0,  # N m
}

ankle_controller_bounds, ankle_controller_map = load_ankle_controller(params)

initial_state = np.array([0.0, 3.0])
timestep = 1e-3
sim_time = 5.0
desired_number_of_steps = 8

poincare_section = []

time_traj, state_traj, completed_steps = simulate_walker(params, initial_state, timestep, sim_time, desired_number_of_steps, ankle_controller_bounds, ankle_controller_map, poincare_section=poincare_section)
print(f"Simulated for {time_traj[-1]} seconds; recorded {completed_steps} steps")
visualize(time_traj, state_traj)

# Build a lookup table of leg angle control actions
num_velocities = 50
initial_velocities = np.linspace(0, np.sqrt(2 * params["gravity"] / params["length"]), num_velocities)
num_actions = 20
actions = np.linspace(np.pi/8, np.pi/7, num_actions)
#
# for vel_idx in range(num_velocities):
#     for action_idx in range(num_actions):
