from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, PillowWriter

from integrators import rk4 as integrator
from models import inverted_pendulum_walker as model


def visualize(time_traj, state_traj, output_name="assignment_2"):
    # Generate an animation of the walker walking, from the perspective as an inverted pendulum
    # Inputs:
    #   time_traj: n-length array of time values
    #   state_traj: 2xn array of state values that correspond to the times in time_traj at the same index
    #   output_name: name of output directory
    # Output: None, displays and saves an animation

    fig, ax = plt.subplots(figsize=(8, 5), layout="constrained")

    def draw_frame(index):
        # The massless swing leg is repositioned instantaneously at each impact.
        model.visualize(state_traj[:, index], params, ax=ax)
        ax.set_title(f"t = {time_traj[index]:.2f} s")

    # Simulate at a small timestep, but render only 25 frames per second.
    fps = 25
    frame_stride = round(1 / (fps * timestep))
    frame_indices = list(range(0, time_traj.size, frame_stride))
    if frame_indices[-1] != time_traj.size - 1:
        frame_indices.append(time_traj.size - 1)

    animation = FuncAnimation(
        fig, draw_frame, frames=frame_indices, interval=1000 / fps, repeat=False
    )
    output = Path(f"output-assignment2/{output_name}")
    output.mkdir(parents=True, exist_ok=True)
    animation.save(output / "walker.gif", writer=PillowWriter(fps=fps))

    # To save an MP4 instead, install FFmpeg and use:
    # animation.save(output / "walker.mp4", writer="ffmpeg", fps=fps)
    print(f"Saved {output / 'walker.gif'}.")
    plt.show()


def simulate_walker(params, initial_state, timestep, sim_time, desired_number_of_steps, ankle_controller_map, ankle_controller_bounds, angle_of_attack_velocities, angle_of_attack_actions, poincare_section=None):
    # Simulate the walker for either some number of steps or some time, whichever comes first
    # Input:
    #   params: dict of params as generated by generate_params()
    #   initial_state: 2x1 array, initial state of the system
    #   timestep: time between steps; usually something like 1e-3, in seconds
    #   sim_time: maximum time of simulation, in seconds
    #   desired_number_of_steps: maximum number of steps the walker can take
    #   ankle_controller_map: 100x100 array representing where to enable ankle controller
    #   ankle_controller_bounds: 2x100 array representing the limits of the ankle_controller_map
    #   angle_of_attack_velocities: n-length array of velocities to match with angle_of_attack_actions
    #   angle_of_attack_actions: n-length array of angles to apply when the velocity at theta=0 matches one of those in angle_of_attack_velocities
    #   poincare_map: if a list is provided, angular velocities that occur when the pendulum is at angle 0 are appended
    # Output: length-n array of times; 2xn array of state trajectory; number of completed steps

    n_timesteps = round(sim_time / timestep) + 1
    time_traj = np.arange(n_timesteps) * timestep
    state_traj = np.zeros((2, n_timesteps))
    state_traj[:, 0] = initial_state
    completed_steps = 0

    # Simulation loop.
    for step, t in enumerate(time_traj[:-1]):
        state = state_traj[:, step]

        if model.ankle_torque_guard(state, params, ankle_controller_map, ankle_controller_bounds):
            model.update_ankle_torque(state, params)
        else:
            params["ankle_torque"] = 0.0  # need to reset to disable control

        #next_state = state + timestep * model.dynamics(t, state, params)
        next_state = integrator.integrate_step(params, model, state, t, timestep)

        if model.poincare_map_guard(state, next_state, params):
            # Update angle of attack controller
            params["angle_of_attack"] = angle_of_attack_actions[np.argmin(np.abs(state[1] - angle_of_attack_velocities))]
            if poincare_section is not None:
                # Calculate the velocity at the map angle using energy
                _, vertical_potential = model.calculate_energy(np.array([0,0]), params)
                next_kinetic, next_potential = model.calculate_energy(next_state, params)
                intersect_kinetic = (next_kinetic + next_potential) - vertical_potential
                intersect_ang_vel = (
                    np.sqrt(intersect_kinetic / (0.5 * params["mass"]))
                    / params["length"]
                )
                poincare_section.append(intersect_ang_vel)


        if model.step_transition_guard(state, next_state, params):
            next_state = model.step_transition_dynamics(next_state, params)
            completed_steps += 1

        state_traj[:, step + 1] = next_state
        if completed_steps == desired_number_of_steps:
            break

    time_traj = time_traj[: step + 2]
    state_traj = state_traj[:, : step + 2]
    return time_traj, state_traj, completed_steps


def calculate_ankle_roa(params):
    # Determine RoA of the ankle controller
    # Inputs:
    #   params: dict of params as generated by generate_params()

    timestep = 1e-3
    sim_time = 3.0

    num_angles = 100
    initial_angles = np.linspace(
        -params["angle_of_attack"] + params["incline"], params["angle_of_attack"] + params["incline"], num_angles
    )
    num_velocities = 100
    initial_velocities = np.linspace(-2, 2, num_velocities)

    dummy_controller_bounds = np.vstack((initial_angles, initial_velocities))
    dummy_controller_map = np.ones((num_angles,num_velocities))

    stop_map = np.ones((initial_angles.size, initial_velocities.size))
    for ang_idx in range(initial_angles.size):
        print(f"Calculating ankle controller RoA: {100*ang_idx/initial_angles.size:.2f}% done")
        initial_angle = initial_angles[ang_idx]
        for ang_vel_idx in range(initial_velocities.size):
            initial_ang_vel = initial_velocities[ang_vel_idx]
            initial_state = np.array([initial_angle, initial_ang_vel])
            time_traj, state_traj, completed_steps = simulate_walker(
                params,
                initial_state,
                timestep,
                sim_time,
                1,
                dummy_controller_map,
                dummy_controller_bounds,
                np.array([0]),
                np.array([params["angle_of_attack"]])
            )
            # Tracking the number of steps actually makes this correlation super easy
            # If a step was taken, then we know that the ankle controller wasn't able to slow the walker to a stop
            # Also, if the final state isn't near static vertical, then we know it must have gone off the rails
            if completed_steps > 0 or np.linalg.norm(state_traj[:,-1]) > 0.10:
                stop_map[ang_idx, ang_vel_idx] = 0

    # Save region of attraction for future use in one file
    # Save the bounds of the map in another file
    params_hash = model.hash_params(params)
    controller_output = Path("output-assignment2/controller_data")
    controller_output.mkdir(parents=True, exist_ok=True)
    np.save(controller_output / f"map_{params_hash}", stop_map)
    combined_bounds = np.vstack((initial_angles, initial_velocities))
    np.save(controller_output / f"bounds_{params_hash}", combined_bounds)

    # Generate a plot showing this RoA
    plt.figure()
    im = plt.imshow(stop_map.T, origin="lower", extent=(initial_angles[0],initial_angles[-1],initial_velocities[0],initial_velocities[-1]))
    plt.gca().set_aspect((initial_angles[-1] - initial_angles[0]) / (initial_velocities[-1] - initial_velocities[0]))
    plt.xlabel("Initial Angle (radians)")
    plt.ylabel("Initial Velocity (rad/s)")
    plt.title("Region of Stoppage")

    # Finish and display/save the plot
    plt.tight_layout()
    plt.savefig(controller_output / "stop_map.png")
    # plt.show()


def load_ankle_controller(params):
    # Load the Region of Attraction data for the walker's ankle torque controller
    # Inputs:
    #   params: dict of params as generated by generate_params()
    # Outputs: stop map (100x100), bounds (2x100)

    params_hash = model.hash_params(params)

    map_path = Path(f"output-assignment2/controller_data/map_{params_hash}.npy")
    bounds_path = Path(f"output-assignment2/controller_data/bounds_{params_hash}.npy")
    if not (map_path.exists() and bounds_path.exists()):
        # Calculate new ankle controller RoA data
        calculate_ankle_roa(params)

    stop_map = np.load(map_path)
    bounds = np.load(bounds_path)

    return stop_map, bounds


def plot_poincare_section(poincare_section):
    # Plot the step-to-step points of the Poincare section (e.g. (x0,x1), (x1,x2), (x2,x3), ...)
    # Inputs:
    #   poincare_map: list of angular velocity values that the system experienced at the same angle
    # Output: None, saves a plot

    if len(poincare_section) < 2:
        plt.title("Return Map (Failed)")
        poincare_path = Path("output-assignment2/assignment_2/return_map.png")
        plt.savefig(poincare_path)
        print("Not enough points in Poincare section; did we reach a good attractor?")
    else:
        plt.figure()
        min_vel = min(poincare_section)
        max_vel = max(poincare_section)
        plt.plot(
            [min_vel * 0.9, 1.1 * max_vel],
            [0.9 * min_vel, 1.1 * max_vel],
            label="Identity Line",
        )
        plt.xlabel("Previous value of Angular Velocity (rad/s)")
        plt.ylabel("Next value of Angular Velocity (rad/s)")
        plt.legend()
        plt.plot(
            poincare_section[:-1],
            poincare_section[1:],
            "rx:",
        )
        plt.show()

        # Estimate the fixed point automatically by looking at the most recent Poincare point
        fixed_point_vel = poincare_section[-1]
        print(f"Computer-estimated fixed point: {fixed_point_vel}")


# Fixed controls for this visualization example.
params = model.generate_params()

ankle_controller_map, ankle_controller_bounds = load_ankle_controller(params)

initial_state = np.array([0.0, 1.6])
timestep = 1e-3
sim_time = 5.0
desired_number_of_steps = 8

poincare_section = []

time_traj, state_traj, completed_steps = simulate_walker(
        params,
        initial_state,
        timestep,
        sim_time,
        desired_number_of_steps,
        ankle_controller_map,
        ankle_controller_bounds,
        np.array([0]),
        np.array([params["angle_of_attack"]]),
        poincare_section=poincare_section,
    )

print(f"Simulated for {time_traj[-1]} seconds; recorded {completed_steps} steps")
visualize(time_traj, state_traj)


# Build a lookup table of leg angle control actions
print("Building step angle table")
max_initial_velocity = np.sqrt(2 * params["gravity"] / params["length"])
num_velocities = 50
initial_velocities = np.linspace(0, max_initial_velocity, num_velocities)
num_actions = 10
actions = np.linspace(np.pi/8, np.pi/7, num_actions)

next_vel_table = np.zeros((num_velocities, num_actions), dtype=int)

# Constant simulation properties
timestep = 1e-3
sim_time = 5.0
desired_number_of_steps = 2  # We expect there to be one step, but we'll look at the Poincare section before the second one

for vel_idx in range(num_velocities):
    print(f"Table construction {100 * (vel_idx / num_velocities):.2f}% done")
    for act_idx in range(num_actions):
        # Just to make sure we start with the same params every time
        # Fixed controls for this visualization example.
        params = model.generate_params()

        initial_velocity = initial_velocities[vel_idx]
        action = actions[act_idx]
        params["angle_of_attack"] = action
        initial_state = np.array([0.0, initial_velocity])

        poincare_section = []

        time_traj, state_traj, completed_steps = simulate_walker(
            params,
            initial_state,
            timestep,
            sim_time,
            desired_number_of_steps,
            ankle_controller_map,
            ankle_controller_bounds,
            np.array([0]),
            np.array([params["angle_of_attack"]]),
            poincare_section=poincare_section,
        )

        # If the Poincare section didn't register anything, then this IC leads to stability or a failure state
        if len(poincare_section) == 0:
            if abs(state_traj[0, -1]) < 1/num_velocities and abs(state_traj[1, -1]) < 1/num_velocities:
                # Stable
                next_vel_table[vel_idx][act_idx] = 0
            else:
                next_vel_table[vel_idx][act_idx] = -1
        else:
            # Since we're using the velocity values directly, equivalence between velocities should be within a tolerance
            # We could put the next velocities into the table directly, but it will be easier to manage if we use indices
            nearest_initial_vel_idx = np.argmin(
                np.abs(initial_velocities - poincare_section[0])
            )
            next_vel_table[vel_idx][act_idx] = int(nearest_initial_vel_idx)

# Create a table showing the next velocities
# We need to switch from indices to real next velocities
indexable_next_vel_table = next_vel_table.copy()
indexable_next_vel_table[indexable_next_vel_table == -1] = 0
next_vel_value_table = initial_velocities[indexable_next_vel_table]
next_vel_value_table[next_vel_table == -1] = -1
im = plt.imshow(next_vel_value_table, origin="lower", extent=(actions[0],actions[-1],0,max_initial_velocity))
plt.gca().set_aspect((actions[-1] - actions[0]) / (max_initial_velocity - 0))
cbar = plt.gcf().colorbar(im)
cbar.set_label('Next angular velocity',size=12,rotation=270)
plt.xlabel("Control angle (radians)")
plt.ylabel("Angular velocity at $\\theta = 0$ (rad/s)")
plt.title("Control Table\nVelocity of -1 denotes failure")
plt.tight_layout()
plt.savefig(Path("output-assignment2/assignment_2/next_vel_table.png"))
# plt.show()


# It may be easier to work with this data if we reversed it
# Table of all possible states that could lead to a given velocity (and control actions, too)
# This will probably be jagged, so it might be easier if we represented it as a graph instead
print("Assembling reverse-state graph")
root_vel_graph = {}
for vel_idx in range(num_velocities):
    root_pos = np.nonzero(next_vel_table == vel_idx)
    zipped_pos = zip(root_pos[0].tolist(), root_pos[1].tolist())
    root_vel_graph[vel_idx] = list(zipped_pos)


# Analyzing the number of steps to get to stability for different initial conditions will be best performed with the following lists:
# Most number of steps possible to get to stability per velocity (num_velocities,)
# Least number of steps possible to get to stability per velocity (num_velocities,)
# Actions at each velocity required to get to stability in the most number of steps (num_velocities,)
# Actions at each velocity required to get to stability in the least number of steps (num_velocities,)
print("Organizing angle of attack policies")

# Do some searching to find the number of steps to get to stability
most_steps = -1 * np.ones((num_velocities,), dtype=int)
most_steps[0] = 0
most_steps_actions = -1 * np.ones((num_velocities,), dtype=int)
least_steps = 1000 * np.ones((num_velocities,), dtype=int)
least_steps[0] = 0
least_steps_actions = -1 * np.ones((num_velocities,), dtype=int)

stack = [0]
while len(stack) > 0:
    state = stack.pop()
    for prev_state, prev_action in root_vel_graph[state]:
        if prev_state != 0:  # Block the infinite loop at 0
            if most_steps[prev_state] < most_steps[state] + 1:
                most_steps[prev_state] = most_steps[state] + 1
                most_steps_actions[prev_state] = prev_action
            if least_steps[prev_state] > least_steps[state] + 1:
                least_steps[prev_state] = least_steps[state] + 1
                least_steps_actions[prev_state] = prev_action

            stack.append(prev_state)

# print("Most steps: ", most_steps)
# print("Most steps actions: ", most_steps_actions)

least_steps[least_steps == 1000] = -1
# print("Least steps: ", least_steps)
# print("Least steps actions: ", least_steps_actions)

# Plot the steps
plt.figure()
for s in range(np.max(most_steps),0,-1):
    for vel_idx in range(num_velocities):
        if most_steps[vel_idx] == s:
            plt.plot((s, s-1), (initial_velocities[vel_idx], initial_velocities[next_vel_table[vel_idx, most_steps_actions[vel_idx]]]), 'g-')
plt.plot(most_steps, initial_velocities, "bo")
plt.title("Most Steps Required for Stability")
plt.xlabel("Steps before stability")
plt.ylabel("Angular velocity at $\\theta = 0$")
plt.savefig(Path("output-assignment2/assignment_2/most_steps.png"))

plt.figure()
for s in range(np.max(least_steps),0,-1):
    for vel_idx in range(num_velocities):
        if least_steps[vel_idx] == s:
            plt.plot((s, s-1), (initial_velocities[vel_idx], initial_velocities[next_vel_table[vel_idx, least_steps_actions[vel_idx]]]), 'g-')
plt.plot(least_steps, initial_velocities, "bo")
plt.title("Least Steps Required for Stability")
plt.xlabel("Steps before stability")
plt.ylabel("Angular velocity at $\\theta = 0$")
plt.savefig(Path("output-assignment2/assignment_2/least_steps.png"))


# Create a graph to visualize all the connections
# This is just pure connections, not the values of actions that actually lead to these connections
plt.figure()
t = -np.linspace(-np.pi/2, np.pi/2,25)
# Mess with t a little bit to put more points around 0, which makes it look smoother in this plot
t = ((np.pi/2) / np.pow(np.pi/2,3)) * np.pow(t,3)
for vel_idx in range(num_velocities):
    vel = initial_velocities[vel_idx]
    for act_idx in range(num_actions):
        # Draw an arc going to the next node
        next_vel_idx = next_vel_table[vel_idx,act_idx]
        switch = 1
        col = 'g'
        next_vel = initial_velocities[next_vel_idx]
        if next_vel_idx == -1:
            switch = -1
            col = 'r'
            next_vel = -1
        rad = (vel - next_vel) / 2
        plt.plot(switch * abs(rad) * np.cos(t), ((vel + next_vel) / 2) + rad * np.sin(t), col+'-', alpha=1/num_actions)
plt.plot(np.zeros((num_velocities,)), initial_velocities, "bo")
plt.plot(0, -1, 'bx')
plt.title("Poincare Section Velocity Graph")
plt.ylabel("Angular velocity at $\\theta = 0$")
plt.savefig(Path("output-assignment2/assignment_2/poincare.png"))

# Plot a trajectory of the walker walking at least 3 steps
print("Simulating walker with active step control")
# We can pick the initial condition to ensure this
initial_state = np.array([0,max_initial_velocity])
desired_number_of_steps = 10
params = model.generate_params()

time_traj, state_traj, completed_steps = simulate_walker(
    params,
    initial_state,
    timestep,
    sim_time,
    desired_number_of_steps,
    ankle_controller_map,
    ankle_controller_bounds,
    initial_velocities,
    actions[least_steps_actions]
)
print(f"Least-steps walker completed {completed_steps} steps")

plt.figure()
plt.plot(state_traj[0,:], state_traj[1,:], 'k:')
plt.plot(state_traj[0,:], state_traj[1,:], 'bo', alpha=0.15)
plt.title(f"Walker walking {completed_steps} steps")
plt.xlabel("Angle")
plt.ylabel("Angular velocity")
plt.savefig(Path("output-assignment2/assignment_2/walking_phase.png"))

plt.figure()
plt.plot(time_traj, state_traj[0,:])
plt.title("Walker Angle vs Time")
plt.xlabel("Time, seconds")
plt.ylabel("Walker Angle, radians")
plt.savefig(Path("output-assignment2/assignment_2/walking_time.png"))


# Plot a trajectory of the walker walking as many steps as possible
time_traj, state_traj, completed_steps = simulate_walker(
    params,
    initial_state,
    timestep,
    sim_time,
    desired_number_of_steps,
    ankle_controller_map,
    ankle_controller_bounds,
    initial_velocities,
    actions[most_steps_actions]
)
print(f"Most-steps walker completed {completed_steps} steps")

plt.figure()
plt.plot(state_traj[0,:], state_traj[1,:], 'k:')
plt.plot(state_traj[0,:], state_traj[1,:], 'bo', alpha=0.15)
plt.title(f"Walker walking {completed_steps} steps")
plt.xlabel("Angle")
plt.ylabel("Angular velocity")
plt.savefig(Path("output-assignment2/assignment_2/walking_most_phase.png"))

plt.figure()
plt.plot(time_traj, state_traj[0,:])
plt.title("Walker Angle vs Time")
plt.xlabel("Time, seconds")
plt.ylabel("Walker Angle, radians")
plt.savefig(Path("output-assignment2/assignment_2/walking_most_time.png"))

