"""InvertedPendulumWalker starter model, with visualization provided.

Implement the model functions for Assignment 2. The visualizer works independently
of those functions; it draws a supplied state without advancing the simulation.
"""

import os

import matplotlib.pyplot as plt
import numpy as np


def generate_params():
    # Generate a dict of default params to be used by the model
    # Input: None
    # Output: dict of params
    
    params = {
        "gravity": 9.81,  # m/s^2
        "length": 1.0,  # m
        "mass": 1.0,  # kg
        "incline": 0.06,  # rad
        "angle_of_attack": np.pi / 8,  # rad
        "ankle_torque": 0.0,  # N m
    }
    return params


def hash_params(params):
    # Generate a hash based on params relevant to the ankle controller
    # Used to save controller data between sessions
    # So I was using hash() to do this but that isn't the same between sessions
    # Basically, this is a unique identifying string
    # Inputs:
    #   params: dict as generated by generate_params()
    # Output: Unique identifier of gravity, length, mass, incline, and angle_of_attack

    return f"{params["gravity"]:.2f}_{params["length"]:.2f}_{params["mass"]:.2f}_{params["incline"]:.2f}_{params["angle_of_attack"]:.2f}".replace(".","-")


def poincare_map_guard(previous_state, next_state, params):
    # Guard to determine whether to add a state to the Poincare map
    # Inputs:
    #   previous_state: state before this instant
    #   next_state: upcoming state of this instant
    #   params: dict of params as generated by generate_params
    # Output: bool

    map_theta = 0.0
    return previous_state[0] < map_theta <= next_state[0]


def ankle_torque_guard(state, params, ankle_controller_map, ankle_controller_bounds):
    # Check whether ankle torque control should be applied
    # Inputs:
    #   state: 2x1 vector representing the inverted pendulum state
    #   params: dict of params as generated by generate_params()
    #   ankle_controller_map: 100x100 map of where to enable ankle torque
    #   ankle_controller_bounds: 2x100 array representing the limits of the map
    # Output: bool
    
    if not (np.min(ankle_controller_bounds[0,:]) <= state[0] <= np.max(ankle_controller_bounds[0,:])) or not (np.min(ankle_controller_bounds[1,:]) <= state[1] <= np.max(ankle_controller_bounds[1,:])):
        # Not within the ranges of our data
        return False

    nearest_angle_idx = np.argmin(np.abs(ankle_controller_bounds[0,:] - state[0]))
    nearest_velocity_idx = np.argmin(np.abs(ankle_controller_bounds[1,:] - state[1]))

    return ankle_controller_map[nearest_angle_idx, nearest_velocity_idx] == 1


def update_ankle_torque(state, params):
    # Use ankle torque to perform feedback linearization
    # Inputs:
    #   t: time value for this instant
    #   state: 2x1 vector representing the inverted pendulum state
    #   params: dict of params as generated by generate_params()
    # Output: None; updates params

    gravity = params["gravity"]
    length = params["length"]
    mass = params["mass"]

    angle = state[0]
    angular_velocity = state[1]

    pendulum_acceleration = (mass * gravity * length * np.sin(angle))# / (mass * length**2)
    pos_control = -angle * 10  # TODO: update these controller gains with more specific numbers
    deriv_control = -angular_velocity * 10

    # We can enforce the ankle torque limits here, too
    ankle_torque = -pendulum_acceleration + deriv_control + pos_control
    params["ankle_torque"] = max(
        -0.1 * mass * length * gravity,
        min(ankle_torque, 0.05 * mass * length * gravity),
    )

def dynamics(t, state, params):
    # Implement the inverted-pendulum-walker dynamics
    # Inputs:
    #   t: time value for this instant
    #   state: 2x1 vector representing the inverted pendulum state
    #   params: dict of params as generated by generate_params()
    # Output: 2x1 array representing the derivative of the state
    
    gravity = params["gravity"]
    length = params["length"]
    mass = params["mass"]

    angle = state[0]
    angular_velocity = state[1]

    # Enforce ankle torque limits
    # We can do that in the controller too, but we might as well make extra sure
    ankle_torque = max(-0.1 * mass * length * gravity, min(params["ankle_torque"], 0.05 * mass * length * gravity))

    angular_acceleration = (
        mass * gravity * length * np.sin(angle)
    ) / (mass * length**2) + ankle_torque

    state_derivative = np.array([angular_velocity, angular_acceleration])
    return state_derivative


def step_transition_guard(previous_state, next_state, params):
    # Detect whether the event (changing the angle of attack) should be invoked
    # Inputs:
    #   previous_state: state (2x1 array) before this instant
    #   next_state: state (2x1 array) after this instant
    #   params: dict of params as generated by generate_params()
    # Output: boolean

    # We need to check whether the walker's next leg went from above the ground to penetrating the ground between the states

    prev_abs_angle = previous_state[0]
    next_abs_angle = next_state[0]

    prev_rel_angle = prev_abs_angle - params["incline"]
    next_rel_angle = next_abs_angle - params["incline"]

    return prev_rel_angle < params["angle_of_attack"] and next_rel_angle > params["angle_of_attack"]


def step_transition_dynamics(state, params):
    # Change state and params to implement control when the event is invoked
    # Inputs:
    #   state: 2x1 array representing the state of the inverted pendulum
    #   params: dict of params as generated by generate_params()
    # Output: New state to replace the provided state

    # Enforce angle of attack limits, just to be extra sure
    angle_of_attack = max(np.pi / 8, min(params["angle_of_attack"], np.pi / 7))

    # We can assume that the event (switching legs) does need to happen
    # We need to calculate the exact point when the leg struck the ground
    # Assuming that energy is conserved
    this_kinetic, this_potential = calculate_energy(state, params)
    this_total_energy = this_kinetic + this_potential
    # At the contact state, the pendulum must have had a relative angle equal to the angle of attack
    contact_potential_energy = (
        params["gravity"]
        * params["mass"]
        * np.cos(angle_of_attack + params["incline"])
        * params["length"]
    )
    # Solve for the contact kinetic energy
    contact_kinetic_energy = this_total_energy - contact_potential_energy
    contact_ang_vel = (
        np.sqrt(contact_kinetic_energy / (0.5 * params["mass"]))
        / params["length"]
    )
    # Projecting the previous velocity onto the arc of the new spoke to preserve the tangent component:
    angular_velocity = contact_ang_vel * np.cos(2 * angle_of_attack)

    # Create a copy of state and replace its values
    new_state = state.copy()
    new_state[0] = -angle_of_attack + params["incline"]
    new_state[1] = angular_velocity
    
    return new_state


def calculate_energy(state, params):
    # Calculate the energy for a certain state of this system
    # Energy for this system is kind of awkward because it's always rotating down a slope
    # So, in one sense, we start with infinite gravitational potential energy and
    # We're also losing energy with every collision because they're modeled as being plastic
    # Inputs:
    #   state: 2xn array of states
    #   params: params dict as generated by generate_params()
    # Output: n-length arrays of kinetic and potential energy

    angle = state[0]
    angular_velocity = state[1]

    # We will assume that gravitational potential energy is calculated from the point of contact with the slope
    kinetic_energy = (
        0.5 * params["mass"] * np.pow(angular_velocity * params["length"], 2)
    )
    potential_energy = (
        params["gravity"] * params["mass"] * np.cos(angle) * params["length"]
    )
    return kinetic_energy, potential_energy


def visualize(
    state,
    params,
    ax=None,
    *,
    show_swing=True,
    stance_position=(0.0, 0.0),
    view_limits=None,
):
    """Draw one walker pose and return a Matplotlib Axes.

    Parameters
    ----------
    state : array-like, shape (2,)
        [theta, angular_velocity], in radians and radians/second. Theta is
        measured clockwise from upward vertical; positive x points right.
    params : dict
        ``length`` is the leg length in meters. ``incline`` is the ground's
        downhill slope angle in radians (positive slopes descend to the right).
        ``angle_of_attack`` is HALF the angle between the stance and forward swing
        legs, in radians; it is needed only when show_swing=True.
        ``ankle_torque`` (optional, default 0) is displayed in N m, with positive
        torque acting in the positive theta direction. Other keys are ignored.
    ax : matplotlib.axes.Axes, optional
        Axes to clear and reuse. If omitted, create a figure. This function
        neither shows nor saves it: use plt.show() or ax.figure.savefig(...).
    show_swing : bool
        Draw a straight forward swing leg at the supplied angle_of_attack. Set False
        while the swing leg is held clear or while balancing. Swing motion is
        not part of the two-state model and is not inferred from theta.
    stance_position : pair of floats
        Current stance foot's (x, y) in meters, default (0, 0). The two-state
        model does not track translation; supply foot positions if desired.
        Ground passes through this point at the supplied incline.
    view_limits : (xmin, xmax, ymin, ymax), optional
        Fixed camera bounds in meters. By default the view follows the stance
        foot with bounds that fit both legs at any angle. Supply the same bounds
        each frame for a stationary world view.

    Notes
    -----
    Draws the supplied pose; contact events belong in the simulation.
    Reuse ax for frame sequences; use evenly spaced simulation times for playback
    at a fixed frame rate, and pass the parameters actually used at each frame.
    """
    state = np.asarray(state, dtype=float)
    foot = np.asarray(stance_position, dtype=float)
    if state.shape != (2,) or not np.all(np.isfinite(state)):
        raise ValueError("state must contain two finite values: [theta, velocity].")
    if foot.shape != (2,) or not np.all(np.isfinite(foot)):
        raise ValueError("stance_position must contain two finite values: [x, y].")
    length = float(params["length"])
    incline = float(params["incline"])
    torque = float(params.get("ankle_torque", 0.0))
    if not np.isfinite(length) or length <= 0:
        raise ValueError("length must be finite and positive.")
    if not np.isfinite(incline) or abs(incline) >= np.pi / 2:
        raise ValueError("incline must be finite and between -pi/2 and pi/2.")
    if not np.isfinite(torque):
        raise ValueError("ankle_torque must be finite.")
    if show_swing:
        angle_of_attack = float(params["angle_of_attack"])
        if not np.isfinite(angle_of_attack):
            raise ValueError("angle_of_attack must be finite.")

    if view_limits is None:
        radius = 2.15 * length
        view_limits = (
            foot[0] - radius,
            foot[0] + radius,
            foot[1] - radius,
            foot[1] + radius,
        )
    limits = np.asarray(view_limits, dtype=float)
    if (
        limits.shape != (4,)
        or not np.all(np.isfinite(limits))
        or limits[0] >= limits[1]
        or limits[2] >= limits[3]
    ):
        raise ValueError(
            "view_limits must be (xmin, xmax, ymin, ymax) with increasing bounds."
        )

    if ax is None:
        _, ax = plt.subplots(figsize=(6, 6), layout="constrained")
    ax.clear()
    theta, angular_velocity = state
    hub = foot + length * np.array([np.sin(theta), np.cos(theta)])

    ground_x = np.array(limits[:2])
    ground_y = foot[1] - np.tan(incline) * (ground_x - foot[0])
    ax.fill_between(ground_x, ground_y, limits[2], color="#eee7dc", zorder=0)
    ax.plot(ground_x, ground_y, color="#7b6651", linewidth=2, label="Ground")
    ax.plot(
        [foot[0], foot[0]],
        [foot[1], foot[1] + 1.25 * length],
        ":",
        color="0.7",
        linewidth=1,
        label="Vertical",
    )

    if show_swing:
        swing_angle = theta - 2 * angle_of_attack
        swing_foot = hub - length * np.array([np.sin(swing_angle), np.cos(swing_angle)])
        swing_color = "#df8a25"
        ax.plot(
            [hub[0], swing_foot[0]],
            [hub[1], swing_foot[1]],
            "--",
            color=swing_color,
            linewidth=2.5,
            label="Swing leg",
            zorder=3,
        )
        ax.plot(
            *swing_foot,
            "o",
            color=swing_color,
            markersize=7,
            zorder=4,
            label="Swing foot",
        )

    stance_color = "#23699b"
    ax.plot(
        [foot[0], hub[0]],
        [foot[1], hub[1]],
        color=stance_color,
        linewidth=4,
        label="Stance leg",
        zorder=4,
    )
    ax.plot(*foot, "s", color="#333333", markersize=8, zorder=5, label="Stance foot")
    ax.plot(
        *hub,
        "o",
        color=stance_color,
        markeredgecolor="white",
        markersize=17,
        zorder=6,
        label="Hub",
    )
    ax.text(
        0.03,
        0.97,
        f"$\\theta$ = {theta:.3f} rad\n"
        f"$\\dot\\theta$ = {angular_velocity:.3f} rad/s\n"
        f"$\\tau$ = {torque:.3f} N m",
        transform=ax.transAxes,
        va="top",
        fontsize=10,
        bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.85},
    )
    ax.set(
        xlim=limits[:2],
        ylim=limits[2:],
        xlabel="x (m)",
        ylabel="y (m)",
        title="Inverted pendulum walker",
    )
    ax.set_aspect("equal", adjustable="box")
    return ax
